### ISSUE TITLE
Lacks any kind of authnetication method.

### ISSUE THREAD

**Issue by lanceofwhichwedream** [janko-m/shrine-gridfs#1]
MongoDB supports and recommends the use of authentication as a security measure, but I don't see that your gem has it at this time. Is this a feature you are working to include?

**Comment by janko** [comment]
How does authentication look like with the raw mongo gem?

**Comment by janko** [comment]
As I expected, [authentication](https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-admin-tasks/#authentication) is done by passing username and password when initializing a `Mongo::Client`. Since the user is in charge of initializing the `Mongo::Client` themselves, that means they can configure any authentication they want, and just pass that authenticated `Mongo::Client` object to `Shrine::Storage::Gridfs`.
